# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x0bmodels.book\"\xa0\x01\n\x04\x42ook\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\x12\x12\n\x05title\x18\x02 \x01(\tH\x00\x88\x01\x01\x12\x13\n\x06\x61uthor\x18\x03 \x01(\tH\x01\x88\x01\x01\x12&\n\x05genre\x18\x04 \x01(\x0e\x32\x12.models.book.GenreH\x02\x88\x01\x01\x12\x11\n\x04year\x18\x05 \x01(\x05H\x03\x88\x01\x01\x42\x08\n\x06_titleB\t\n\x07_authorB\x08\n\x06_genreB\x07\n\x05_year*z\n\x05Genre\x12\x0b\n\x07UNKNOWN\x10\x00\x12\n\n\x06\x41\x43TION\x10\x01\x12\r\n\tADVENTURE\x10\x02\x12\n\n\x06\x43OMEDY\x10\x03\x12\t\n\x05\x44RAMA\x10\x04\x12\x0b\n\x07\x46\x41NTASY\x10\x05\x12\n\n\x06HORROR\x10\x06\x12\x0b\n\x07ROMANCE\x10\x07\x12\x0c\n\x08THRILLER\x10\x08\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _GENRE._serialized_start=190
  _GENRE._serialized_end=312
  _BOOK._serialized_start=28
  _BOOK._serialized_end=188
# @@protoc_insertion_point(module_scope)
