# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inventory_item.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import service.book_pb2 as book__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14inventory_item.proto\x12\x15models.inventory_item\x1a\nbook.proto\"\x7f\n\rInventoryItem\x12\x14\n\x0cinventory_id\x18\x01 \x01(\x05\x12!\n\x04\x62ook\x18\x02 \x01(\x0b\x32\x11.models.book.BookH\x00\x12-\n\x06status\x18\x03 \x01(\x0e\x32\x1d.models.inventory_item.StatusB\x06\n\x04item*\"\n\x06Status\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'inventory_item_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STATUS._serialized_start=188
  _STATUS._serialized_end=222
  _INVENTORYITEM._serialized_start=59
  _INVENTORYITEM._serialized_end=186
# @@protoc_insertion_point(module_scope)
